// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemplateRoleAccess.API.Models.Context;

#nullable disable

namespace TemplateRoleAccess.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230206034144_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TemplateRoleAccess.API.Models.Entities.Account", b =>
                {
                    b.Property<string>("NIK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NIK");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("TemplateRoleAccess.API.Models.Entities.AccountRole", b =>
                {
                    b.Property<string>("AccountNIK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("AccountNIK", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccountRoles");
                });

            modelBuilder.Entity("TemplateRoleAccess.API.Models.Entities.Departement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Manager_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Manager_Id");

                    b.ToTable("Departements");
                });

            modelBuilder.Entity("TemplateRoleAccess.API.Models.Entities.Employee", b =>
                {
                    b.Property<string>("NIK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("Date");

                    b.Property<int?>("Departement_Id")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("NIK");

                    b.HasIndex("Departement_Id");

                    b.HasIndex("Manager_Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TemplateRoleAccess.API.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TemplateRoleAccess.API.Models.Entities.Account", b =>
                {
                    b.HasOne("TemplateRoleAccess.API.Models.Entities.Employee", "Employee")
                        .WithOne("Account")
                        .HasForeignKey("TemplateRoleAccess.API.Models.Entities.Account", "NIK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TemplateRoleAccess.API.Models.Entities.AccountRole", b =>
                {
                    b.HasOne("TemplateRoleAccess.API.Models.Entities.Account", "Accounts")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountNIK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TemplateRoleAccess.API.Models.Entities.Role", "Roles")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("TemplateRoleAccess.API.Models.Entities.Departement", b =>
                {
                    b.HasOne("TemplateRoleAccess.API.Models.Entities.Employee", "ManagerDepartement")
                        .WithMany()
                        .HasForeignKey("Manager_Id");

                    b.Navigation("ManagerDepartement");
                });

            modelBuilder.Entity("TemplateRoleAccess.API.Models.Entities.Employee", b =>
                {
                    b.HasOne("TemplateRoleAccess.API.Models.Entities.Departement", "Departements")
                        .WithMany()
                        .HasForeignKey("Departement_Id");

                    b.HasOne("TemplateRoleAccess.API.Models.Entities.Employee", "ManagerEmployees")
                        .WithMany()
                        .HasForeignKey("Manager_Id");

                    b.Navigation("Departements");

                    b.Navigation("ManagerEmployees");
                });

            modelBuilder.Entity("TemplateRoleAccess.API.Models.Entities.Account", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("TemplateRoleAccess.API.Models.Entities.Employee", b =>
                {
                    b.Navigation("Account");
                });

            modelBuilder.Entity("TemplateRoleAccess.API.Models.Entities.Role", b =>
                {
                    b.Navigation("AccountRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
